### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by naufalboys** [wangbm/MTCNN-Tensorflow#12]
I encountered an error like this : Error from tools import IoU

**Comment by naufalboys** [comment]
Add the directory to your Environment (Path)

**Comment by nyingnying** [comment]
what directory? i have activated cv environment and run python gen_shuffle_data.py 12 on /MTCNN-Tensorflow/prepare_data but the error is still the same :(

**Comment by nyingnying** [comment]
drag tools.py from master to the prepare_data directory

**Comment by galuhputraa** [comment]
> 

thank u i solved it by ur reply
